kafka:
  ## Habilita la persistencia
  persistence:
    enabled: true
    size: 1Gi # Ajusta el tamaño según tus necesidades

  ## Configuración de autenticación básica
  auth:
    clientProtocol: sasl
    saslMechanisms: plain
    saslInterBrokerProtocol: plain
    saslJaasClientUsers: user1,user2
    saslJaasClientPasswords: password1,password2

  ## Lista de topics a crear automáticamente
  topics:
  - name: topic-t1
    partitions: 1
    replicationFactor: 1

  ## Configuraciones de recursos para optimizar el uso
  # resources:
  #   limits:
  #     cpu: "2"
  #     memory: "2048Mi"
  #   requests:
  #     cpu: "1"
  #     memory: "1536Mi"

  ## Habilita el acceso externo (Si es necesario para tu caso de uso)
  service:
    type: LoadBalancer
    port: 9094
    nodePorts:
      client: 31090

  ## Configuraciones de métricas para monitoreo
  metrics:
    kafka:
      enabled: true
    jmx:
      enabled: true
