## Configure the Kafka cluster
replicaCount: 1

## Kafka Configuration Overrides
configOverrides:
  server:
    - "auto.create.topics.enable=true"

## Configure Kafka Topics
topics:
  - name: topic-test1
    partitions: 1
    replicationFactor: 1

## Persistence configuration
persistence:
  enabled: true
  size: 1Gi
  storageClass: "" # Leave as an empty string to use the default storage class

## Kafka Client Users (add this section)
auth:
  clientUsers:
    - user1 # Assuming user1 is your desired client user
  clientPasswords:
    - password1 # in bas64 format is ubi3fS3LII
